### PR TITLE
Ruby warning fix: instance variable used before initialize

### LINKED ISSUE #62: Ruby warning - unused variable
wasabi/parser.rb:120: warning: assigned but unused variable - root_elements

### PR DESCRIPTION
**Pull request by chaymaeBZ**
Fixes #62

### CODE REVIEW

File: lib/wasabi/parser.rb [hunk 1]
```diff
@@ -319,14 +319,13 @@ def section(section_name)
...
     def sections
-      return @sections if @sections
-
-      sections = {}
-      document.root.element_children.each do |node|
-        (sections[node.name] ||= []) << node
-      end
-
-      @sections = sections
+      @sections ||= begin
```
Comment (bvicenzo) [inline lib/wasabi/parser.rb:322]: @chaymaeBZ @olleolleolle To simplify this code, we could use the [Enumerable#group_by](https://apidock.com/ruby/Enumerable/group_by) method... Wdyta?

```rb
@sections ||= document.root.element_children.group_by { |node| node.name }
```

Comment (olleolleolle) [reply lib/wasabi/parser.rb:322]: I think that sounds fine, if you make a PR, you can see if all tests still pass, would be nice.

Comment (bvicenzo) [reply lib/wasabi/parser.rb:322]: @olleolleolle Done: https://github.com/savonrb/wasabi/pull/90
