### PR TITLE
Fix input/output for `style="rpc"` operations

### LINKED ISSUE #118: 4.0 release breaks integration with `style="rpc"` operations
If I understand it correctly, PR #114 added a check in the `style` attribute of an operation to know if it's an `document`.

https://github.com/savonrb/wasabi/blob/3bf250213e842c1207d39ee7891288160686574f/lib/wasabi/parser.rb#L147

Apparently, a comparison is missing here, so it's always considering that it's a `document` style.
A solution is to just compare with the desired value:

```ruby
 soap_document = soap_operation["style"] == "document" if soap_operation
```

### PR DESCRIPTION
**Pull request by hss-mateus**
Closes #118

I provided an example WSDL (`spec/fixtures/rpc.xml`) based on a real one from a service that I use.

Until version 3.8, the gem was generating the following operation:

```ruby
{
  example_operation: {
    action: "urn:ExampleInterface-ExamplePortType#ExampleOperation",
    input: "ExampleOperation",
    output: "ExampleOperation",
    namespace_identifier: "tns"
  }
}
```

As for 4.0, it has changed to:

```ruby
{
  example_operation: {
    action: "urn:ExampleInterface-ExamplePortType#ExampleOperation",
    input: "ExampleOperationRequest",
    output: "ExampleOperationResponse",
    namespace_identifier: "tns"
  }
}
```

This resulted in a different body when using it in savon:

```diff
<soap:Body>
-  <ExampleOperation>
+  <ExampleOperationRequest>
    ...
-  </ExampleOperation>
+  </ExampleOperationRequest>
</soap:Body>
```

I disabled that behaviour for `style="rpc"` operations, but I'm not sure if this is the right solution.

### CODE REVIEW

File: lib/wasabi/parser.rb [hunk 1]
```diff
@@ -260,8 +260,13 @@ def input_output_for(operation, input_output)
         end
 
         message_ns_id, message_type = nil
-        message_ns_id = port_message_ns_id
-        message_type = port_message_type
+
+        soap_operation = operation.element_children.find { |node| node.name == 'operation' }
+
+        if soap_operation.nil? || soap_operation['style'] != 'rpc'
```
Comment (pcai) [inline lib/wasabi/parser.rb:266]: mind explaining the change here? why do we branch into here only if nil soap operation or the style is (presumably) document

Comment (hss-mateus) [reply lib/wasabi/parser.rb:266]: This could be refactored to `unless soap_operation&.get_attribute('style') == 'rpc'`

It just disables the behavior introduced in 4.0 for RPC operations. When the value is `nil` or `document` it keeps the current behavior.

**Comment by tvdeyen** [comment]
We have the same issue with Wasabi 5 (which automatically installed with savon 2.15.). We jumped from Wasabi 3.8 to 5.0 in a minor update. 

@pcai please consider to release a Savon v3 with the breaking changes (httpi v4 and wasabi v5) and release a new 2.16 of savon that pins wasabi and httpi back to working releases.

We now solved it for now by pinning `wasabi` to `< 4`.

**Comment by pcai** [comment]
Thanks @hss-mateus - I confirmed the new spec passes in 3.8 and this PR, but fails in 5.0.1. Will make a release today or tomorrow with this fix

**Comment by hss-mateus** [comment]
Nice, thanks for reviewing it!
